/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from "react";
import { useGeneratedContent } from "../hooks/useGeneratedContent";
import PageHeader from "../components/PageHeader";
import StatusBadge from "../components/StatusBadge";
import EmptyState from "../components/EmptyState";
import { useAppStore } from "../../store";
import {
  Sparkles,
  Check,
  X,
  FileText,
  Linkedin,
  Instagram,
  Mail,
  ChevronRight,
  HelpCircle,
} from "lucide-react";

export default function GeneratedContentPage() {
  const {
    contentList,
    loading,
    error,
    approveContent,
    rejectContent,
    refresh,
  } = useGeneratedContent();
  const { setCursorHovered } = useAppStore();
  const [filter, setFilter] = useState<
    "all" | "awaiting_approval" | "approved"
  >("all");

  // Track active sub-tab for *each* generated content card by keeping a map of contentId -> activePlatform
  const [activeTabs, setActiveTabs] = useState<
    Record<string, "blog" | "linkedin" | "instagram" | "newsletter">
  >({});

  const getActiveTab = (id: string) => activeTabs[id] || "blog";

  const setCardTab = (
    id: string,
    tab: "blog" | "linkedin" | "instagram" | "newsletter",
  ) => {
    setActiveTabs((prev) => ({ ...prev, [id]: tab }));
  };

  const filteredContent = contentList.filter((gc) => {
    if (filter === "all") return true;
    return gc.status === filter;
  });

  return (
    <div className="space-y-8 animate-fade-in">
      <PageHeader
        title="AI AGENT FACTORY"
        subtitle="Approve or regenerate multi-channel copywriting generated by the GoTrip LLM engines"
        onRefresh={refresh}
        isRefreshing={loading}
      />

      {/* Filter tabs */}
      <div className="flex border-b-3 border-black bg-white dark:bg-black select-none max-w-sm">
        {(["all", "awaiting_approval", "approved"] as const).map((f) => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            onMouseEnter={() => setCursorHovered(true)}
            onMouseLeave={() => setCursorHovered(false)}
            className={`flex-1 py-2.5 text-center font-mono text-[9px] font-black uppercase tracking-wider cursor-pointer border-t-3 border-x-3 border-transparent transition-all ${
              filter === f
                ? "bg-[#E2FF00] text-black border-black border-b-[3px] border-b-white z-10"
                : "text-gray-400 hover:text-black dark:text-gray-500 dark:hover:text-[#E2FF00]"
            }`}
          >
            {f === "all"
              ? "VIEW ALL"
              : f === "awaiting_approval"
                ? "AWAITING"
                : "RELEASED"}
          </button>
        ))}
      </div>

      {loading ? (
        <div className="text-center py-20 font-mono text-xs text-gray-500 select-none animate-pulse">
          AI COPYWRITING AGENTS ARE SPINNING CHANNELS...
        </div>
      ) : filteredContent.length === 0 ? (
        <EmptyState
          message="NO CAMPAIGN OUTPUTS FOUND"
          description="Ready campaigns will populate here as soon as incoming RSS articles are authorized by operators."
        />
      ) : (
        <div className="grid grid-cols-1 xl:grid-cols-2 gap-8">
          {filteredContent.map((gc) => {
            const currentTab = getActiveTab(gc.id);

            return (
              <div
                key={gc.id}
                className="border-3 border-black bg-white dark:bg-[#121210] p-6 neo-shadow-lg space-y-6 flex flex-col justify-between"
              >
                {/* Header segment */}
                <div className="space-y-2">
                  <div className="flex flex-col md:flex-row md:items-center justify-between gap-3 select-none">
                    <span className="bg-black text-[#E2FF00] font-mono text-[8px] font-black p-1.5 border border-black uppercase inline-block leading-none shrink-0 tracking-wider">
                      ID: {gc.id}
                    </span>
                    <StatusBadge status={gc.status} />
                  </div>
                  <h3 className="font-syne font-black text-md md:text-lg uppercase text-black dark:text-white leading-tight mt-1">
                    {gc.articleTitle}
                  </h3>
                </div>

                {/* Platform Selector buttons */}
                <div className="flex flex-wrap border-b-2 border-black bg-gray-50 dark:bg-black p-0.5 select-none">
                  {[
                    { id: "blog" as const, label: "BLOG POST", icon: FileText },
                    {
                      id: "linkedin" as const,
                      label: "LINKEDIN",
                      icon: Linkedin,
                    },
                    {
                      id: "instagram" as const,
                      label: "INSTAGRAM",
                      icon: Instagram,
                    },
                    {
                      id: "newsletter" as const,
                      label: "NEWSLETTER",
                      icon: Mail,
                    },
                  ].map((plat) => {
                    const isSelected = currentTab === plat.id;
                    const PlatIcon = plat.icon;

                    return (
                      <button
                        key={plat.id}
                        onClick={() => setCardTab(gc.id, plat.id)}
                        onMouseEnter={() => setCursorHovered(true)}
                        onMouseLeave={() => setCursorHovered(false)}
                        className={`flex items-center space-x-1.5 px-3 py-2 font-mono text-[8px] font-black uppercase tracking-wider cursor-pointer border-r border-[#111111]/10 ${
                          isSelected
                            ? "bg-black text-[#E2FF00] dark:bg-[#E2FF00] dark:text-black"
                            : "text-gray-400 hover:text-black dark:text-gray-500"
                        }`}
                      >
                        <PlatIcon className="w-3 h-3 shrink-0" />
                        <span>{plat.label}</span>
                      </button>
                    );
                  })}
                </div>

                {/* Previews panel */}
                <div className="bg-[#DFDFD8]/20 dark:bg-black/30 border border-black/10 p-5 min-h-[160px] max-h-[220px] overflow-y-auto font-display text-xs leading-relaxed text-gray-700 select-all selection:bg-[#E2FF00] selection:text-black">
                  {currentTab === "blog" && (
                    <div className="space-y-2 whitespace-pre-wrap">
                      {gc.blogContent}
                    </div>
                  )}
                  {currentTab === "linkedin" && (
                    <div className="italic text-[#006699] select-all whitespace-pre-wrap font-sans">
                      {gc.linkedinPost}
                    </div>
                  )}
                  {currentTab === "instagram" && (
                    <div className="text-pink-700 select-all whitespace-pre-wrap leading-tight">
                      {gc.instagramPost}
                    </div>
                  )}
                  {currentTab === "newsletter" && (
                    <div className="bg-white border border-gray-200 p-3 select-all rounded-none text-black">
                      <p className="font-mono text-[9px] text-[#E23E26] font-bold mb-1 underline">
                        NEWSLETTER MAIL PREVIEW
                      </p>
                      <p className="font-sans leading-relaxed whitespace-pre-wrap">
                        {gc.newsletter}
                      </p>
                    </div>
                  )}
                </div>

                {/* Decision Panel */}
                <div className="pt-4 border-t border-black/10 flex justify-between items-center select-none">
                  <div>
                    <span className="font-mono text-[8px] text-gray-400 uppercase font-black">
                      AI CAMPAIGN VERDICT
                    </span>
                  </div>

                  {gc.status === "awaiting_approval" ? (
                    <div className="flex gap-2">
                      <button
                        onClick={() => approveContent(gc.id)}
                        onMouseEnter={() => setCursorHovered(true)}
                        onMouseLeave={() => setCursorHovered(false)}
                        className="py-1 px-3 bg-[#E2FF00] hover:bg-black hover:text-white text-black border-2 border-black font-mono text-[9px] font-black uppercase transition-all cursor-pointer flex items-center space-x-1"
                      >
                        <Check className="w-3.5 h-3.5 text-[#E23E26]" />
                        <span>RELEASE CHANNELS</span>
                      </button>
                      <button
                        onClick={() => rejectContent(gc.id)}
                        onMouseEnter={() => setCursorHovered(true)}
                        onMouseLeave={() => setCursorHovered(false)}
                        className="py-1 px-3 bg-white hover:bg-[#E23E26] hover:text-white text-black border-2 border-black font-mono text-[9px] font-black uppercase transition-all cursor-pointer flex items-center space-x-1"
                      >
                        <X className="w-3.5 h-3.5 text-red-600" />
                        <span>REGENERATE</span>
                      </button>
                    </div>
                  ) : (
                    <span className="font-mono text-[9px] text-gray-400 uppercase italic">
                      RELEASED APPROVED STATE
                    </span>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
